language: java
jdk:
  - oraclejdk14
stages:
  - name: compile
  - name: test
  - name: deploy
    if: branch = master AND type = push
jobs:
  include:
    - stage: compile
      script: mvn clean compile
    - stage: test
      script: mvn clean test
    - stage: deploy
      script: mvn clean heroku:deploy
      after_script: heroku ps:scale worker=1 -a telegramnotifierbot