spring:
  profiles.include: slack-common
slack:
  customer:
    debt.webhook: ${CUSTOMER_DEBT_SLACK_WEBHOOK}
    payment.webhook: ${CUSTOMER_PAYMENT_SLACK_WEBHOOK}
    birthday.webhook: ${CUSTOMER_BIRTHDAY_SLACK_WEBHOOK}
  employee.webhook: ${EMPLOYEE_SLACK_WEBHOOK}