slack:
  customer:
    # Workdays at 13:00 - send customer info to slack
    debt.cron: 0 0 13 * * MON-FRI
    payment.cron: 0 0 13 * * MON-FRI
  employee:
    birthday:
      # Workdays at 9:00 - send daily birthday info to slack
      dailyCron: 0 0 12 * * MON-FRI
      # Every 1st of new month at 9:00 - send monthly birthday info to slack
      monthlyCron: 0 0 12 1 * ?