slack:
  customer:
    # Workdays at 13:00 - send customer info to slack
    # eg. 10:00 cron with server offset of 3 is 13:00 Moscow time
    debt.cron: 0 0 13 * * MON-FRI
    receivable.cron: 0 0 13 * * MON-FRI
  employee:
    birthday:
      # Workdays at 9:00 - send daily birthday info to slack
      dailyCron: 0 0 12 * * MON-FRI
      # Every 1st of new month at 9:00 - send monthly birthday info to slack
      monthlyCron: 0 0 12 1 * ?