spring:
  profiles.active: prod
  datasource:
    driver-class-name: org.postgresql.Driver
    initialization-mode: never
    jpa:
      database-platform: org.hibernate.dialect.PostgreSQLDialect
      show-sql: true
      hibernate:
        ddl-auto: update
    url: ${JDBC_DATABASE_URL}
    username: ${JDBC_DATABASE_USERNAME}
    password: ${JDBC_DATABASE_PASSWORD}
json:
  customer:
    debt:
      # URL to customer debt JSON
      url: ${CUSTOMER_DEBT_JSON_URL}
      # Workdays at 11:55 - update
      cron: 0 55 11 * * MON-FRI
    receivable:
      # URL to customer receivable JSON
      url: ${CUSTOMER_RECEIVABLE_JSON_URL}
      # Workdays at 11:55 - update
      cron: 0 55 11 * * MON-FRI
  employee:
    url: ${EMPLOYEE_URL}
    # Workdays at 6:30 - update
    cron: 0 30 6 * * MON-FRI
moex:
  # MOEX RUB/USD and RUB/EUR exchange data
  url: https://iss.moex.com//iss/statistics/engines/currency/markets/selt/rates
  usd: CBRF_USD_LAST (double)
  eur: CBRF_EUR_LAST (double)