spring:
  profiles.active: prod
  datasource:
    driver-class-name: org.postgresql.Driver
    initialization-mode: never
    jpa:
      database-platform: org.hibernate.dialect.PostgreSQLDialect
      show-sql: true
      hibernate:
        ddl-auto: update
    url: ${JDBC_DATABASE_URL}
    username: ${JDBC_DATABASE_USERNAME}
    password: ${JDBC_DATABASE_PASSWORD}
common:
  timezone: Europe/Moscow
json:
  customer:
    debt:
      cron: 0 55 11 * * MON-FRI
    receivable:
      cron: 0 55 11 * * MON-FRI
  employee:
    cron: 0 30 6 * * MON-FRI
moex:
  url: https://iss.moex.com//iss/statistics/engines/currency/markets/selt/rates
  usd: CBRF_USD_LAST (double)
  eur: CBRF_EUR_LAST (double)