spring:
  profiles.include: telegram-dev
  datasource:
    url: jdbc:postgresql://localhost:5432/telegram_bot_test
    username: user
    password: password
external:
  customer:
    debt.url:
    operation.url:
  employee.url: