slack:
  customer:
    # Workdays at 10:00 - send customer info to slack
    # Cron time is based on environment time, so for Moscow time it is Moscow time - server offset time
    # eg. 10:00 cron with server offset of 3 is 13:00 Moscow time
    debt.cron: 0 0 10 * * MON-FRI
    receivable.cron: 0 * * * * ?
  employee:
    birthday:
      # Workdays at 9:00 - send daily birthday info to slack
      dailyCron: 0 0 9 * * MON-FRI
      # Every 1st of new month at 9:00 - send monthly birthday info to slack
      monthlyCron: 0 0 9 1 * ?