spring:
  profiles.active: dev
  datasource:
    driver-class-name: org.postgresql.Driver
    initialization-mode: never
    jpa:
      database-platform: org.hibernate.dialect.PostgreSQLDialect
      show-sql: true
      hibernate:
        ddl-auto: update
    url: ${JDBC_DATABASE_URL}
common:
  timezone: Europe/Moscow
external:
  customer:
    debt:
      cron: 0 55 11 * * MON-FRI
    receivable:
      cron: 0 55 11 * * MON-FRI
  employee:
    cron: 0 30 6 * * MON-FRI
moex:
  url: https://iss.moex.com//iss/statistics/engines/currency/markets/selt/rates
  usd: CBRF_USD_LAST (double)
  eur: CBRF_EUR_LAST (double)
---
spring:
  profiles: demo
  profiles.include: telegram-common
  datasource:
    # PostgreSQL syntax is not recommended in general - see https://stackoverflow.com/a/24235439/13716599
    url: jdbc:h2:mem:testdb;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE
    driverClassName: org.h2.Driver
telegram.bot.token: