spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url:
    username:
    password:
    initialization-mode: never

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update