spring:
  profiles.include: slack-common
slack:
  customer:
    debt.webhook: ${CUSTOMER_DEBT_SLACK_WEBHOOK}
    receivable.webhook: ${CUSTOMER_PAYMENT_SLACK_WEBHOOK}
  employee.birthday.webhook: ${EMPLOYEE_BIRTHDAY_SLACK_WEBHOOK}