spring:
  profiles.include: slack-common
slack:
  # Webhook of chat that receives customer debt info
  customer:
    debt.webhook:
    # Webhook of chat that receives customer payment info
    receivable.webhook:
  # Webhook of chat that receives birthday info
  employee.birthday.webhook: